version: '3'
services:
  qanightlyresults:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      QANB_BASEURL: "localhost"
      QANB_DB_HOST: "localhost" 
      QANB_DB_USERNAME: "myDBUser"
      QANB_DB_PASSWORD: "myDBPasswd"
      QANB_DB_NAME: "myDBName"
